/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.23
 * Generated at: 2022-10-26 01:38:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class company_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1666331988706L));
    _jspx_dependants.put("/head.jsp", Long.valueOf(1666332454432L));
    _jspx_dependants.put("/nav.jsp", Long.valueOf(1666746368928L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>맘스터치</title>\r\n");
      out.write("<!-- 메타포 -->\r\n");
      out.write("<!-- 오픈그래프 -->\r\n");
      out.write("<!-- 파비콘 -->\r\n");
      out.write("<link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"wiz_logo/apple-icon-60x60.png\">\r\n");
      out.write("<!-- 각 종 플러그인과 설정 파일 -->\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Nanum+Gothic&family=Noto+Sans+KR&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<!-- 구형 브라우저 html5태그 인식 -->\r\n");
      out.write("<script src=\"js/html5shiv.js\"></script>\r\n");
      out.write("<!-- 구형 브라우저에서 css animation 인식 -->\r\n");
      out.write("<script src=\"js/prefixfree.min.js\"></script>\r\n");
      out.write("<!-- 구형 브라우저에서 미디어쿼리 인식 -->\r\n");
      out.write("<script src=\"js/respond.min.js\"></script>\r\n");
      out.write("<!-- jquery 플러그인 연결 -->\r\n");
      out.write("<script src=\"js/jquery-1.11.1.js\"></script>");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/reset2.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/header.css\">\r\n");
      out.write("<style>\r\n");
      out.write("/* header.css */\r\n");
      out.write(".hd { position: fixed;}\r\n");
      out.write("/* content */\r\n");
      out.write("    .vs { clear:both; width: 100%; height:300px; overflow: hidden; }\r\n");
      out.write("    .vs img { display:block; width: 100%; height:auto; }\r\n");
      out.write("    .bread { clear:both; width: 100%; line-height: 60px; border-bottom:3px solid #eee; }\r\n");
      out.write("    .bread_fr { width: 1200px; margin: 0 auto; }\r\n");
      out.write("    .page { clear:both; width: 100%; min-height:100vh;}\r\n");
      out.write("    .page:after { content:\"\"; display:block; clear:both; }\r\n");
      out.write("    .page_wrap { width: 1200px; margin: 0 auto; }\r\n");
      out.write("    .content { display:none; }\r\n");
      out.write("    .content:target { display:block; }\r\n");
      out.write("\r\n");
      out.write("    .page_title { padding-top: 1em; text-align: center;}\r\n");
      out.write("    .page_title1 { padding-top: 1em; text-align: center; margin-bottom: 30px;}\r\n");
      out.write("    .page_title2 { text-align: left;}\r\n");
      out.write("    .home { color:#333; }\r\n");
      out.write("    \r\n");
      out.write("    .to_top { position:fixed; bottom:80px; right:80px; z-index:999; \r\n");
      out.write("    background-color:rgba(11,11,11,0.75); color:#fff; display:block; width: 60px;\r\n");
      out.write("    height: 60px; line-height: 60px; text-align: center; font-size:20px; border-radius:32px; visibility:hidden; transition-duration:0.8s; }\r\n");
      out.write("    .to_top:hover { background-color: #ff9933; }\r\n");
      out.write("    .to_top.on { visibility: visible; }\r\n");
      out.write("\r\n");
      out.write("    .pic_lst { clear:both; width: 100%; }\r\n");
      out.write("    .pic_lst li { width: 30%; float:left; margin-right: 5%; margin-bottom: 60px; position:relative; }\r\n");
      out.write("    .pic_lst li a { display:block; position:relative; }\r\n");
      out.write("    .pic_lst li a .pic_fr { width: 100%; height: 220px; overflow:hidden; background-color:#fff;  }\r\n");
      out.write("    .pic_lst li a img { display:block; width: 100%; height:auto; }\r\n");
      out.write("    .pic_lst li:nth-child(3n) { margin-right: 0; }\r\n");
      out.write("    .pic_tit { line-height:2; overflow:hidden; text-overflow: ellipsis; white-space:nowrap; color:#222; text-align: center;}\r\n");
      out.write("    .pic_com { line-height:2; overflow:hidden; text-overflow: ellipsis; white-space:nowrap; color: #ff9933; text-align: center;}\r\n");
      out.write("    .sale_price { font-size:16px; font-weight: bold; color:red; }\r\n");
      out.write("    .origin_price { text-decoration: line-through; }\r\n");
      out.write("    .pic_hd { position:absolute; top:0; left: 0; z-index:10; width: 100%; height:32px; opacity:0.8; text-shadow:2px 2px 0px #fff, 1px 1px 0px #fff;}\r\n");
      out.write("    .ht_ico { display:block; float:left; width:100px; line-height: 32px; height: 32px; padding-left: 10px; padding-top: 10px; color:#333; }\r\n");
      out.write("\r\n");
      out.write("    .noti_lst {  width: 1200px; float:left; }\r\n");
      out.write("    .noti_lst li { clear:both; height:32px; border-bottom:1px solid #333; box-sizing:border-box; }\r\n");
      out.write("    .noti_lst li:first-child { border-top:2px solid #333; }\r\n");
      out.write("    .noti_lst li:last-child { border-bottom:2px solid #333; }\r\n");
      out.write("    .noti_lst li span { display:block; box-sizing:border-box; float:left; line-height: 32px; font-size:18px; }\r\n");
      out.write("    .noti_num { width: 60px; text-align:center; }\r\n");
      out.write("    .not_tit { width: 950px; overflow:hidden; text-overflow:ellipsis; white-space:nowrap; }\r\n");
      out.write("    .item_hd { font-weight:600; }\r\n");
      out.write("    .not_tit.item_hd { text-align: center; }\r\n");
      out.write("    .not_tit a { display: block; overflow:hidden; text-overflow:ellipsis; white-space:nowrap; padding-right: 12px; color:#333; }\r\n");
      out.write("    .noti_auth { width: 80px; text-align: center; }\r\n");
      out.write("    .noti_date { width: 110px; text-align: center; }  \r\n");
      out.write("\r\n");
      out.write("    .frm { border:2px solid #eee; padding: 24px; width: 1200px; margin:50px auto; }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("    $(document).ready(function(){\r\n");
      out.write("        $(\".to_top\").attr(\"href\", location.href);\r\n");
      out.write("        $(window).scroll(function(){\r\n");
      out.write("            var ht = $(window).height();\r\n");
      out.write("            var tp = $(this).scrollTop();\r\n");
      out.write("            if(tp>=300){\r\n");
      out.write("                $(\".to_top\").addClass(\"on\");\r\n");
      out.write("                $(\".to_top\").attr(\"href\", location.href);\r\n");
      out.write("            } else {\r\n");
      out.write("                $(\".to_top\").removeClass(\"on\");\r\n");
      out.write("                $(\".to_top\").attr(\"href\", location.href);\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    });   \r\n");
      out.write("</script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/footer.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"wrap\">\r\n");
      out.write("<header class=\"hd\">\r\n");
      out.write("    ");
      out.write('\r');
      out.write('\n');

	String id = (String) session.getAttribute("id");
	String email = (String) session.getAttribute("email");
	String name = (String) session.getAttribute("name");
	
	String msg = (String) application.getAttribute("msg");

      out.write("\r\n");
      out.write("<div class=\"hd_wrap\">\r\n");
      out.write("           <a href=\"index.jsp\" class=\"logo\"><img src=\"img/logo.png\" alt=\"로고\"></a>\r\n");
      out.write("           <nav class=\"tnb\">\r\n");
      out.write("           ");

           		if(id !=null && id.equals("admin")){
           
      out.write("\r\n");
      out.write("           \t\t<div>\r\n");
      out.write("           \t\t\t<a href=\"memList.jsp\">회원관리</a>\r\n");
      out.write("           \t\t\t<a href=\"boardList.jsp\">게시판 관리</a>\r\n");
      out.write("               \t\t<a href=\"logout.jsp\">로그아웃</a>\r\n");
      out.write("           \t\t</div>\r\n");
      out.write("           ");

           		} else if(id != null){
           
      out.write("\r\n");
      out.write("           \t\t<div>\r\n");
      out.write("           \t\t\t<span class=\"id_print\">");
      out.print(name );
      out.write("님</span>\r\n");
      out.write("               \t\t<a href=\"logout.jsp\">로그아웃</a>\r\n");
      out.write("               \t\t<a href=\"memInfo.jsp\">회원정보</a>\r\n");
      out.write("               \t</div>\r\n");
      out.write("           ");
 
           		} else {
           	
      out.write("\r\n");
      out.write("           \t\t<div>\r\n");
      out.write("               \t\t<a href=\"login.jsp\">로그인</a>\r\n");
      out.write("               \t\t<a href=\"join.jsp\">회원가입</a>\r\n");
      out.write("               \t</div>\t       \r\n");
      out.write("           ");

           		}
           
      out.write("\r\n");
      out.write("           </nav>\r\n");
      out.write("           <nav class=\"gnb\">\r\n");
      out.write("               <ul>\r\n");
      out.write("                   <li class=\"item1\">\r\n");
      out.write("                       <a href=\"company.jsp#page1\" class=\"main\">브랜드스토리</a>\r\n");
      out.write("                       <ul class=\"sub\">\r\n");
      out.write("                           <li><a href=\"company.jsp#page1\">브랜드 소개</a></li>\r\n");
      out.write("                           <li><a href=\"company.jsp#page2\">공지사항</a></li>\r\n");
      out.write("                           <li><a href=\"company.jsp#page3\">광고 영상</a></li>\r\n");
      out.write("                       </ul>\r\n");
      out.write("                   </li>\r\n");
      out.write("                   <li class=\"item2\">\r\n");
      out.write("                       <a href=\"menu.jsp#page1\" class=\"main\">메뉴</a>\r\n");
      out.write("                       <ul class=\"sub\">\r\n");
      out.write("                           <li><a href=\"menu.jsp#page1\">전체</a></li>\r\n");
      out.write("                           <li><a href=\"menu.jsp#page2\">버거</a></li>\r\n");
      out.write("                           <li><a href=\"menu.jsp#page3\">세트메뉴</a></li>\r\n");
      out.write("                       </ul>\r\n");
      out.write("                   </li>\r\n");
      out.write("                   <li class=\"item3\">\r\n");
      out.write("                       <a href=\"service.jsp#page1\" class=\"main\">프로모션</a>\r\n");
      out.write("                       <ul class=\"sub\">\r\n");
      out.write("                           <li><a href=\"service.jsp#page1\">전체</a></li>\r\n");
      out.write("                           <li><a href=\"service.jsp#page2\">진행중</a></li>\r\n");
      out.write("                           <li><a href=\"service.jsp#page3\">종료</a></li>\r\n");
      out.write("                       </ul>\r\n");
      out.write("                   </li>\r\n");
      out.write("                   <li class=\"item4\">\r\n");
      out.write("                       <a href=\"custom.jsp#page1\" class=\"main\">고객문의</a>\r\n");
      out.write("                       <ul class=\"sub\">\r\n");
      out.write("                           <li><a href=\"custom.jsp#page1\">자주하는 질문</a></li>\r\n");
      out.write("                           <li><a href=\"custom.jsp#page2\">Q/A</a></li>\r\n");
      out.write("                           <li><a href=\"boardList.jsp\">게시판</a></li>\r\n");
      out.write("                       </ul>\r\n");
      out.write("                   </li>\r\n");
      out.write("                   <li class=\"item5\">\r\n");
      out.write("                       <a href=\"map.jsp\" class=\"main\">매장찾기</a>\r\n");
      out.write("                       <ul class=\"sub\">\r\n");
      out.write("                       </ul>\r\n");
      out.write("                   </li>\r\n");
      out.write("               </ul>\r\n");
      out.write("           </nav>\r\n");
      out.write("       </div>");
      out.write("\r\n");
      out.write("</header>\r\n");
      out.write("<div class=\"content\" id=\"page1\">\r\n");
      out.write("    <figure class=\"vs\">\r\n");
      out.write("        <img src=\"img/p_brand_1.jpg\" alt=\"비주얼\">\r\n");
      out.write("    </figure>\r\n");
      out.write("    <div class=\"bread\">\r\n");
      out.write("        <div class=\"bread_ft\">\r\n");
      out.write("            <a href=\"index1.jsp\" class=\"home\">HOME</a> &gt;\r\n");
      out.write("            <select name=\"sel1\" id=\"sel1\" class=\"sel\">\r\n");
      out.write("                <option>브랜드스토리</option>\r\n");
      out.write("                <option value=\"menu.jsp#page1\">메뉴</option>\r\n");
      out.write("                <option value=\"service.jsp#page1\">프로모션</option>\r\n");
      out.write("                <option value=\"custom.jsp#page1\">고객문의</option>\r\n");
      out.write("                <option value=\"map.jsp\">매장찾기</option>\r\n");
      out.write("            </select> &gt;\r\n");
      out.write("            <select name=\"sel2\" id=\"sel2\" class=\"sel\">\r\n");
      out.write("                <option>브랜드소개</option>\r\n");
      out.write("                <option value=\"company.jsp#page2\">공지사항</option>\r\n");
      out.write("                <option value=\"company.jsp#page3\">광고영상</option>\r\n");
      out.write("            </select>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <section class=\"page\">\r\n");
      out.write("        <div class=\"page_wrap\">\r\n");
      out.write("            <h2 class=\"page_title\">브랜드 소개</h2>\r\n");
      out.write("            <div class=\"conetent\">\r\n");
      out.write("                <div class=\"description\">\r\n");
      out.write("                    <h4>대한민국 NO.1을 넘어,<br> 전 세계 NO.1을 꿈꾸는<br>버거&치킨 브랜드 맘스터치 입니다.</h4>\r\n");
      out.write("                </div>\r\n");
      out.write("                <figure class=\"desciption-images\"><img src=\"/assets/images/brand/p_brand_1.jpg\"  alt=\"버거와 치킨 이미지\"></figure>\r\n");
      out.write("                <div class=\"description-more\">\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <h5>Brand Mission</h5>\r\n");
      out.write("                            <p>올바른 음식을 통해 건강, 행복, 즐거운 미래를 만들어갑니다.</p>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li style=\"float: left;\">\r\n");
      out.write("                            <h5 style=\"margin-right: 45px;\">Brand Vision</h5>\r\n");
      out.write("                            <p>정성 어린 한 끼 식사를 준비하는 마음가짐으로 고객 마음속의 NO.1 으로 발돋움 하겠습니다.</p>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <section class=\"section brand-identity\">\r\n");
      out.write("            <header>\r\n");
      out.write("                <h3>브랜드 아이덴티티</h3>\r\n");
      out.write("                <p>맘스터치를 상징하는 두 가지 타입의 로고입니다.<br>고객을 생각하는 정성 어린 맘스터치의 마음을 담고 있습니다.</p>\r\n");
      out.write("            </header>\r\n");
      out.write("            <div class=\"logo\">\r\n");
      out.write("                <div class=\"list\">\r\n");
      out.write("                    <div class=\"item\">\r\n");
      out.write("                        <h4>brand logo</h4><img src=\"../../assets/images/brand/new_logo_brand_1.png\" alt=\"moms touch logo\" style=\"width:30vw;\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"item\">\r\n");
      out.write("                        <img src=\"../../assets/images/brand/new_logo_brand_2.png\" alt=\"moms touch logo\" style=\"width:40vw;\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"item\">\r\n");
      out.write("                        <h4>Color Concept</h4>\r\n");
      out.write("                        <p>고객에게 전달하고자 하는 가치를 따뜻하고 조화롭게 표현하기 위한 비전을 담고 있습니다.<br>세 컬러의 조화로 맘스터치의 “정성”을 표현합니다.</p>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li><img src=\"/assets/images/brand/img_brand_1.jpg\" alt=\"mom’s touch PATTY YELLOW #F2A900\">\r\n");
      out.write("                                <p><span>뛰어난 퀼리티를 지키는<br>치킨패티</span></p>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li><img src=\"/assets/images/brand/img_brand_2.jpg\" alt=\"mom’s touch TOWN GRAY #D7D2CB\">\r\n");
      out.write("                                <p><span>항상 가까이에서 고객을<br>맞이하고자 하는 마음</span></p>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li><img src=\"/assets/images/brand/img_brand_3.jpg\" alt=\"mom’s TOUCH EARTH BROWN #5C4738\">\r\n");
      out.write("                                <p><span>자연을 존중하고 자연이 주는<br>신선함을 담고자 하는 마음</span></p>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <section class=\"section store-identity\">\r\n");
      out.write("            <header>\r\n");
      out.write("                <h3>스토어 아이덴티티</h3>\r\n");
      out.write("                <p>맘스터치 매장은 고객을 향한 정성과 사랑을<br>함축적으로 담아낸 따뜻한 공간입니다. <span>브라운, 그레이 톤으로 안정감을 주었으며 노란색, 붉은 컬러 등 따뜻한 계열의 컬러로 엄마의 사랑을 상징화해 누구나 엄마의 따뜻한 마음과 편안함을 느낄 수 있도록 했습니다</span></p>\r\n");
      out.write("            </header>\r\n");
      out.write("            <div class=\"contents\">\r\n");
      out.write("                <div class=\"swiper-contents\">\r\n");
      out.write("                    <div class=\"swiper-container\">\r\n");
      out.write("                        <div class=\"swiper-wrapper\">\r\n");
      out.write("                            <!--<div class=\"swiper-slide\"><img src=\"/m/assets/images/@temp_franchise_open_condition.jpg\" alt=\"\"></div>\r\n");
      out.write("                            <div class=\"swiper-slide\"><img src=\"/m/assets/images/@temp_franchise_open_condition.jpg\" alt=\"\"></div>-->\r\n");
      out.write("                            <div class=\"swiper-slide\"><img src=\"/assets/images/franchise/p_open_condition_1.jpg\" alt=\"\"></div>\r\n");
      out.write("                            <div class=\"swiper-slide\"><img src=\"/assets/images/franchise/p_open_condition_2.jpg\" alt=\"\"></div>\r\n");
      out.write("                            <div class=\"swiper-slide\"><img src=\"/assets/images/franchise/p_open_condition_3.jpg\" alt=\"\"></div>\r\n");
      out.write("                            <div class=\"swiper-slide\"><img src=\"/assets/images/franchise/p_open_condition_5.jpg\" alt=\"\"></div>\r\n");
      out.write("                            <div class=\"swiper-slide\"><img src=\"/assets/images/franchise/p_open_condition_6.jpg\" alt=\"\"></div>\r\n");
      out.write("                            <div class=\"swiper-slide\"><img src=\"/assets/images/franchise/p_open_condition_7.jpg\" alt=\"\"></div>\r\n");
      out.write("                            <div class=\"swiper-slide\"><img src=\"/assets/images/franchise/p_open_condition_8.jpg\" alt=\"\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"swiper-pagination\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"swiper-button-prev\"></div>\r\n");
      out.write("                    <div class=\"swiper-button-next\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"by\"></div>\r\n");
      out.write("        </section>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"content\" id=\"page2\">\r\n");
      out.write("    <figure class=\"vs\">\r\n");
      out.write("        <img src=\"img/p_brand_1.jpg\" alt=\"비주얼\">\r\n");
      out.write("    </figure>\r\n");
      out.write("    <div class=\"bread\">\r\n");
      out.write("        <div class=\"bread_ft\">\r\n");
      out.write("            <a href=\"index1.jsp\" class=\"home\">HOME</a> &gt;\r\n");
      out.write("            <select name=\"sel3\" id=\"sel3\" class=\"sel\">\r\n");
      out.write("                <option>브랜드스토리</option>\r\n");
      out.write("                <option value=\"menu.jsp#page1\">메뉴</option>\r\n");
      out.write("                <option value=\"service.jsp#page1\">프로모션</option>\r\n");
      out.write("                <option value=\"custom.jsp#page1\">고객문의</option>\r\n");
      out.write("                <option value=\"map.jsp\">매장찾기</option>\r\n");
      out.write("            </select> &gt;\r\n");
      out.write("            <select name=\"sel4\" id=\"sel4\" class=\"sel\">\r\n");
      out.write("                <option>공지사항</option>\r\n");
      out.write("                <option value=\"company.jsp#page1\">브랜드소개</option>\r\n");
      out.write("                <option value=\"company.jsp#page3\">광고영상</option>\r\n");
      out.write("            </select>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <section class=\"page\">\r\n");
      out.write("        <div class=\"page_wrap\">\r\n");
      out.write("            <h2 class=\"page_title1\">공지 사항</h2>\r\n");
      out.write("            <div class=\"con_wrap\">\r\n");
      out.write("                <ul class=\"pic_lst\">\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"\">\r\n");
      out.write("                            <div class=\"pic_fr\"><img src=\"./img/1663321480-LZGRE.jpg\" alt=\"pic1\"></div>\r\n");
      out.write("                            <div class=\"pic_hd\"><span class=\"ht_ico new\"></span><span class=\"starating on\"></span></div>\r\n");
      out.write("                            <p class=\"pic_com\">2022-09-16</p>\r\n");
      out.write("                            <h3 class=\"pic_tit\">맘스터치 9월 버거 신제품 출시</h3>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"\">\r\n");
      out.write("                            <div class=\"pic_fr\"><img src=\"./img/1658302996-DVENX.png\" alt=\"pic2\"></div>\r\n");
      out.write("                            <div class=\"pic_hd\"><span class=\"ht_ico new\"></span><span class=\"starating\"></span></div>\r\n");
      out.write("                            <p class=\"pic_com\">2022-07-20</p>\r\n");
      out.write("                            <h3 class=\"pic_tit\">그릴드 비프버거 출시</h3>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"\">\r\n");
      out.write("                            <div class=\"pic_fr\"><img src=\"./img/1657781500-VVKKB.jpg\" alt=\"pic3\"></div>\r\n");
      out.write("                            <div class=\"pic_hd\"><span class=\"starating on\"></span></div>\r\n");
      out.write("                            <p class=\"pic_com\">2022-07-14</p>\r\n");
      out.write("                            <h3 class=\"pic_tit\">맘스터치 피자앤치킨 창업설명회 안내</h3>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <section class=\"page\">\r\n");
      out.write("                <div class=\"page_wrap\">\r\n");
      out.write("                    <h4 class=\"page_title2\">전체</h4>\r\n");
      out.write("                    <ul class=\"noti_lst\">\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <span class=\"noti_num item_hd\">연번</span>\r\n");
      out.write("                            <span class=\"not_tit item_hd\">제목</span>\r\n");
      out.write("                            <span class=\"noti_auth item_hd\">작성자</span>\r\n");
      out.write("                            <span class=\"noti_date item_hd\">작성일</span>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <span class=\"noti_num\">1</span>\r\n");
      out.write("                            <span class=\"not_tit\"><a href=\"\">트리플딥치즈비프버거 출시!</a></span>\r\n");
      out.write("                            <span class=\"noti_auth\">관리자</span>\r\n");
      out.write("                            <span class=\"noti_date\">2022-09-27</span>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <span class=\"noti_num\">2</span>\r\n");
      out.write("                            <span class=\"not_tit\"><a href=\"\">맘스터치 야채통통치킨버거 출시!</a></span>\r\n");
      out.write("                            <span class=\"noti_auth\">관리자</span>\r\n");
      out.write("                            <span class=\"noti_date\">2022-09-20</span>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <span class=\"noti_num\">3</span>\r\n");
      out.write("                            <span class=\"not_tit\"><a href=\"\">맘스터치 9월 버거 신제품 출시</a></span>\r\n");
      out.write("                            <span class=\"noti_auth\">관리자</span><span class=\"noti_date\">2022-09-16</span>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <span class=\"noti_num\">4</span>\r\n");
      out.write("                            <span class=\"not_tit\"><a href=\"\">맘스터치 고객 여러분들께 안내 드립니다.</a></span>\r\n");
      out.write("                            <span class=\"noti_auth\">관리자</span><span class=\"noti_date\">2022-08-01</span>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <span class=\"noti_num\">5</span>\r\n");
      out.write("                            <span class=\"not_tit\"><a href=\"\">그릴드 비프버거 출시</a></span>\r\n");
      out.write("                            <span class=\"noti_auth\">관리자</span><span class=\"noti_date\">2022-07-20</span>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <span class=\"noti_num\">6</span>\r\n");
      out.write("                            <span class=\"not_tit\"><a href=\"\">맘스터치 피자앤치킨 창업설명회 안내</a></span>\r\n");
      out.write("                            <span class=\"noti_auth\">관리자</span><span class=\"noti_date\">2022-07-14</span>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <span class=\"noti_num\">7</span>\r\n");
      out.write("                            <span class=\"not_tit\"><a href=\"\">맘스터치 단체주문 안내</a></span>\r\n");
      out.write("                            <span class=\"noti_auth\">관리자</span><span class=\"noti_date\">2022-06-07</span>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <span class=\"noti_num\">8</span>\r\n");
      out.write("                            <span class=\"not_tit\"><a href=\"\">맘스터치 소자본 창업 희망 프로젝트</a></span>\r\n");
      out.write("                            <span class=\"noti_auth\">관리자</span><span class=\"noti_date\">2021-11-15</span>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <span class=\"noti_num\">9</span>\r\n");
      out.write("                            <span class=\"not_tit\"><a href=\"\">맘스비 꿀팁 컨테스트 결과 발표</a></span>\r\n");
      out.write("                            <span class=\"noti_auth\">관리자</span><span class=\"noti_date\">2021-08-27</span>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <span class=\"noti_num\">10</span>\r\n");
      out.write("                            <span class=\"not_tit\"><a href=\"\">놓칠 수 없는 맘스터치 주요 소식, 맘스뉴스!</a></span>\r\n");
      out.write("                            <span class=\"noti_auth\">관리자</span><span class=\"noti_date\">2021-07-28</span>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </section>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"content\" id=\"page3\">\r\n");
      out.write("    <figure class=\"vs\">\r\n");
      out.write("        <img src=\"img/p_brand_1.jpg\" alt=\"비주얼\">\r\n");
      out.write("    </figure>\r\n");
      out.write("    <div class=\"bread\">\r\n");
      out.write("        <div class=\"bread_ft\">\r\n");
      out.write("            <a href=\"index1.jsp\" class=\"home\">HOME</a> &gt;\r\n");
      out.write("            <select name=\"sel5\" id=\"sel5\" class=\"sel\">\r\n");
      out.write("                <option>브랜드스토리</option>\r\n");
      out.write("                <option value=\"menu.jsp#page1\">메뉴</option>\r\n");
      out.write("                <option value=\"service.jsp#page1\">프로모션</option>\r\n");
      out.write("                <option value=\"custom.jsp#page1\">고객문의</option>\r\n");
      out.write("                <option value=\"map.jsp\">매장찾기</option>\r\n");
      out.write("            </select> &gt;\r\n");
      out.write("            <select name=\"sel6\" id=\"sel6\" class=\"sel\">\r\n");
      out.write("                <option>광고영상</option>\r\n");
      out.write("                <option value=\"company.jsp#page1\">브랜드소개</option>\r\n");
      out.write("                <option value=\"company.jsp#page2\">공지사항</option>\r\n");
      out.write("            </select>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <section class=\"page\">\r\n");
      out.write("        <div class=\"page_wrap\">\r\n");
      out.write("            <h2 class=\"page_title\">광고 영상</h2>\r\n");
      out.write("            <ul class=\"lst\">\r\n");
      out.write("                <div class=\"form_fr\">\r\n");
      out.write("                    <form name=\"frm1\" action=\"\" method=\"post\" id=\"loginForm\" class=\"frm\">\r\n");
      out.write("                        <table class=\"frm_tb\">\r\n");
      out.write("                            <tbody>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <li class=\"left\">\r\n");
      out.write("                                        <iframe name=\"vdo2\" id=\"vdo2\" width=\"1200\" height=\"690\" src=\"https://www.youtube.com/embed/oX0HBc-pCok\" title=\"MOM’STOUCH ORIGINAL | 엄마를 찾아서 – 걱정하지 마 엄마가 튀겨줄게\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                            </tbody>\r\n");
      out.write("                        </table>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("                <li class=\"right\">\r\n");
      out.write("                    <ul class=\"ico_lst\">\r\n");
      out.write("                        <div class=\"con_wrap\">\r\n");
      out.write("                            <ul class=\"pic_lst\">\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"https://www.youtube.com/embed/oX0HBc-pCok\" target=\"vdo2\">\r\n");
      out.write("                                        <div class=\"pic_fr\"><img src=\"./img/1638164852-SNYSQ.png\" alt=\"pic1\"></div>\r\n");
      out.write("                                        <div class=\"pic_hd\"></span><span class=\"starating\"></span></div>\r\n");
      out.write("                                        <h3 class=\"pic_tit\">MOM’STOUCH ORIGINAL | 엄마를 찾아서 – 걱정하지 마 엄마가 튀겨줄게</h3>\r\n");
      out.write("                                        <p class=\"pic_com\">2021-12-02</p>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"https://www.youtube.com/embed/b43YTcBvyzY\" target=\"vdo2\">\r\n");
      out.write("                                        <div class=\"pic_fr\"><img src=\"./img/1628069915-VEBNG.png\" alt=\"pic2\"></div>\r\n");
      out.write("                                        <div class=\"pic_hd\"></span><span class=\"starating\"></span></div>\r\n");
      out.write("                                        <h3 class=\"pic_tit\">맘스터치 치즈홀릭버거(에멘탈) TVCF 30s</h3>\r\n");
      out.write("                                        <p class=\"pic_com\">2021-08-05</p>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"https://www.youtube.com/embed/DxxgAOtkyDE\" target=\"vdo2\">\r\n");
      out.write("                                        <div class=\"pic_fr\"><img src=\"./img/1620894256-YEYTH.jpg\" alt=\"pic2\"></div>\r\n");
      out.write("                                        <div class=\"pic_hd\"></span><span class=\"starating\"></span></div>\r\n");
      out.write("                                        <h3 class=\"pic_tit\">맘스터치 치즈홀릭버거 TVC(30s)_본편</h3>\r\n");
      out.write("                                        <p class=\"pic_com\">2021-05-04</p>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"https://www.youtube.com/embed/rZWo-R41pf4\" target=\"vdo2\">\r\n");
      out.write("                                        <div class=\"pic_fr\"><img src=\"./img/1620894173-STMKT.jpg\" alt=\"pic2\"></div>\r\n");
      out.write("                                        <div class=\"pic_hd\"></span><span class=\"starating\"></span></div>\r\n");
      out.write("                                        <h3 class=\"pic_tit\">맘스터치 치즈홀릭버거 TVC(15s)_본편</h3>\r\n");
      out.write("                                        <p class=\"pic_com\">2021-05-04</p>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"https://www.youtube.com/embed/6VebumErD3c\" target=\"vdo2\">\r\n");
      out.write("                                        <div class=\"pic_fr\"><img src=\"./img/1620518974-NPYEJ.png\" alt=\"pic2\"></div>\r\n");
      out.write("                                        <div class=\"pic_hd\"></span><span class=\"starating\"></span></div>\r\n");
      out.write("                                        <h3 class=\"pic_tit\">맘스터치 치즈홀릭버거 TVC (15s)_티저</h3>\r\n");
      out.write("                                        <p class=\"pic_com\">2021-05-04</p>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"https://www.youtube.com/embed/PONibbhHzns\" target=\"vdo2\">\r\n");
      out.write("                                        <div class=\"pic_fr\"><img src=\"./img/1617010053-KMMLL.png\" alt=\"pic2\"></div>\r\n");
      out.write("                                        <div class=\"pic_hd\"></span><span class=\"starating\"></span></div>\r\n");
      out.write("                                        <h3 class=\"pic_tit\">내슈빌핫치킨 TVC(30s)_B</h3>\r\n");
      out.write("                                        <p class=\"pic_com\">2020-12-08</p>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"https://www.youtube.com/embed/7tgh4ipRhWQ\" target=\"vdo2\">\r\n");
      out.write("                                        <div class=\"pic_fr\"><img src=\"./img/1617009798-UZNWZ.png\" alt=\"pic2\"></div>\r\n");
      out.write("                                        <div class=\"pic_hd\"></span><span class=\"starating\"></span></div>\r\n");
      out.write("                                        <h3 class=\"pic_tit\">2020 싸이버거 TVC(16년간 3억개편)</h3>\r\n");
      out.write("                                        <p class=\"pic_com\">2020-12-08</p>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"https://www.youtube.com/embed/pzPPteotgtg\" target=\"vdo2\">\r\n");
      out.write("                                        <div class=\"pic_fr\"><img src=\"./img/1617004689-XGRGH.jpg\" alt=\"pic2\"></div>\r\n");
      out.write("                                        <div class=\"pic_hd\"></span><span class=\"starating\"></span></div>\r\n");
      out.write("                                        <h3 class=\"pic_tit\">2019 맘스터치 언빌리버블버거 TVCF (30s)</h3>\r\n");
      out.write("                                        <p class=\"pic_com\">2019-03-28</p>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"https://www.youtube.com/embed/RtixVPqEvdQ\" target=\"vdo2\">\r\n");
      out.write("                                        <div class=\"pic_fr\"><img src=\"./img/1617004374-MNFVK.jpg\" alt=\"pic2\"></div>\r\n");
      out.write("                                        <div class=\"pic_hd\"></span><span class=\"starating\"></span></div>\r\n");
      out.write("                                        <h3 class=\"pic_tit\">2018 맘스터치 인크레더블버거 TVCF (30s)</h3>\r\n");
      out.write("                                        <p class=\"pic_com\">2018-11-13</p>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("</div>\r\n");
      out.write("<script>\r\n");
      out.write("    var sel = document.getElementsByClassName(\"sel\");\r\n");
      out.write("    for(var i=0;i<sel.length;i++){\r\n");
      out.write("        sel[i].addEventListener(\"change\", function(){\r\n");
      out.write("            location.href = this.value;\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("<footer class=\"ft\">\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("<div class=\"ft_wrap\">\r\n");
      out.write("        <div class=\"ft_logo\"><img src=\"img/logo.png\" alt=\"하단로고\"></div>\r\n");
      out.write("        <div class=\"mid_box\">\r\n");
      out.write("            <nav class=\"fnb\">\r\n");
      out.write("                <a href=\"member01.html\">개인정보 처리 방침</a>\r\n");
      out.write("                <a href=\"member02.html\">이용약관</a>\r\n");
      out.write("                <a href=\"member03.html\">이메일무단수집거부</a>\r\n");
      out.write("            </nav>\r\n");
      out.write("            <p class=\"addr\">\r\n");
      out.write("                ㈜맘스터치앤컴퍼니 | 대표이사 | 김동전 사업자등록번호 676-86-00102<br>\r\n");
      out.write("                서울시 강동구 천호대로 1077 이스트센트럴타워 24,25층<br>\r\n");
      out.write("                통신판매업 신고번호 : 제2015-서울강동-0155호<br>\r\n");
      out.write("                대표전화 1661-4205 | 팩스 02-418-0279, 070-4676-0635  \r\n");
      out.write("            </p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <script>\r\n");
      out.write("    function sel_link(sel){\r\n");
      out.write("        location.href = sel.value;\r\n");
      out.write("    }\r\n");
      out.write("    </script>\r\n");
      out.write("</div>>");
      out.write("\r\n");
      out.write("</footer>\r\n");
      out.write("</div>\r\n");
      out.write("<a href=\"#\" class=\"to_top\">↑</a>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
