/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.23
 * Generated at: 2022-10-28 03:34:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1666331988706L));
    _jspx_dependants.put("/head.jsp", Long.valueOf(1666766706036L));
    _jspx_dependants.put("/nav.jsp", Long.valueOf(1666924740349L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>맘스터치</title>\r\n");
      out.write("<!-- 메타포 -->\r\n");
      out.write("<!-- 오픈그래프 -->\r\n");
      out.write("<!-- 파비콘 -->\r\n");
      out.write("<link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"wiz_logo/apple-icon-60x60.png\">\r\n");
      out.write("<!-- 각 종 플러그인과 설정 파일 -->\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Nanum+Gothic&family=Noto+Sans+KR&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<!-- 구형 브라우저 html5태그 인식 -->\r\n");
      out.write("<script src=\"js/html5shiv.js\"></script>\r\n");
      out.write("<!-- 구형 브라우저에서 css animation 인식 -->\r\n");
      out.write("<script src=\"js/prefixfree.min.js\"></script>\r\n");
      out.write("<!-- 구형 브라우저에서 미디어쿼리 인식 -->\r\n");
      out.write("<script src=\"js/respond.min.js\"></script>\r\n");
      out.write("<!-- jquery 플러그인 연결 -->\r\n");
      out.write("<script src=\"js/jquery-1.11.1.js\"></script>");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/reset2.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/header.css\">\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("/* header.css */\r\n");
      out.write("\r\n");
      out.write("/* content */\r\n");
      out.write(".page { clear:both; width: 100%; }\r\n");
      out.write("    .page_wrap { width: 1200px; margin: 0 auto; }\r\n");
      out.write("    #page1, #page3 { background-color:#ececec; }\r\n");
      out.write("    .page_tit { text-align: center; font-size:32px; padding-top:1.2em; padding-bottom: 0.8em; }\r\n");
      out.write("    .lst { clear:both; width: 1200px; }\r\n");
      out.write("    .lst:after { content:\"\"; display:block; clear: both;}\r\n");
      out.write("    .lst li { margin-bottom: 40px; }\r\n");
      out.write("    .lst li.left { float:left; width: 816px; height: 459px; }\r\n");
      out.write("    .lst li.right { float:right; width:350px; height: 459px; }\r\n");
      out.write("    .ico_lst { clear:both; width: 100%; overflow:hidden; }\r\n");
      out.write("    .ico_lst li a { display:block; background-repeat: no-repeat; background-position:0px center; background-size:auto 80%; padding-left: 55px; }\r\n");
      out.write("    .ico_lst li a.icon1 { background-image: url(\"./icon/free-icon-one-6055946.png\"); }\r\n");
      out.write("    .ico_lst li a.icon2 { background-image: url(\"./icon/free-icon-two-6055966.png\");}\r\n");
      out.write("    .ico_lst li a.icon3 { background-image: url(\"./icon/free-icon-three-6055984.png\"); }\r\n");
      out.write("    .cate_tit { color:#222; font-size:20px; padding-bottom: 0.5em; }\r\n");
      out.write("    .cate_com { color:#222; font-size:14px; overflow:hidden; white-space:nowrap; text-overflow:ellipsis; }\r\n");
      out.write("\r\n");
      out.write("    #page2 { background-color: rgba(230, 248, 255, 0.5); }\r\n");
      out.write("    .pic_lst { clear:both; width: 100%; padding-bottom: 80px; }\r\n");
      out.write("    .pic_lst:after { content:\"\"; display:block; clear:both; }\r\n");
      out.write("    .pic_lst li { float:left; position:relative; margin-bottom: 40px; }\r\n");
      out.write("    .pic_lst li a { display:block; width: 360px; margin-right: 40px; overflow: hidden; height: 300px; }\r\n");
      out.write("    .pic_lst li a img { display:block; width:600px; margin-left: -120px; transition-duration:0.8s; }\r\n");
      out.write("    .pic_lst li a:hover img { margin-left: 0; }\r\n");
      out.write("    .pic_lst li a .hv_box { width: 360px; height: 300px; color:#fff; opacity:0; position:absolute; top:0; left: 0; z-index:10; transition-duration:0.8s; background-color:transparent; }\r\n");
      out.write("    .pic_lst li a:hover .hv_box { opacity:1; }\r\n");
      out.write("    .pic_tit { position:absolute; top:30px; left: 30px; text-shadow:0px 0px 3px red; }\r\n");
      out.write("    .pic_com { position:absolute; right:30px; bottom:30px; text-shadow:0px 0px 3px blue; }\r\n");
      out.write("\r\n");
      out.write("    #page3 { background-repeat: no-repeat; \r\n");
      out.write("    background-size: cover; \r\n");
      out.write("    background-position:center center; height: 100vh; background-image:url(\"./img/bg_partners.jpg\"); overflow:hidden; }\r\n");
      out.write("    #page3 .page_wrap { width: 100%; }\r\n");
      out.write("    .circle_lst { clear:both; width: 4455px; }\r\n");
      out.write("    .circle_lst li { width: 200px; height: 200px; position:relative; border-radius:120px; overflow:hidden; background-color: #fff;\r\n");
      out.write("    float:left; margin:28px;  }\r\n");
      out.write("    .circle_lst.lst2 li { float:right; }\r\n");
      out.write("    .circle_lst li a { display:block; width: 100%; height: 100%; }\r\n");
      out.write("    .circle_lst li a img { display:block; width:160px; height:auto; \r\n");
      out.write("    position:absolute; top:50%; left: 20px; z-index:11; margin-top: -28px; }\r\n");
      out.write("\r\n");
      out.write("    /* footer */\r\n");
      out.write("    \r\n");
      out.write("    </style>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/footer.css\">\r\n");
      out.write("    <script>\r\n");
      out.write("    $(document).ready(function(){\r\n");
      out.write("        $(window).scroll(function(){\r\n");
      out.write("            var ht = $(window).height();\r\n");
      out.write("            var tp = $(this).scrollTop();\r\n");
      out.write("            if(tp>=600){\r\n");
      out.write("                $(\".hd\").css(\"position\",\"fixed\");\r\n");
      out.write("            } else {\r\n");
      out.write("                $(\".hd\").css(\"position\",\"absolute\");\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("        $\r\n");
      out.write("        $(\"<ul class='circle_lst lst2'></ul>\").insertAfter($(\".circle_lst\"));\r\n");
      out.write("        $lst1_obj = $(\".circle_lst li\").clone();\r\n");
      out.write("        $(\".circle_lst.lst2\").append($lst1_obj);\r\n");
      out.write("    });     \r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"wrap\">\r\n");
      out.write("    <header class=\"hd\">\r\n");
      out.write("        ");
      out.write('\r');
      out.write('\n');

	String id = (String) session.getAttribute("id");
	String email = (String) session.getAttribute("email");
	String name = (String) session.getAttribute("name");
	
	String msg = (String) application.getAttribute("msg");

      out.write("\r\n");
      out.write("<div class=\"hd_wrap\">\r\n");
      out.write("           <a href=\"index.jsp\" class=\"logo\"><img src=\"img/logo.png\" alt=\"로고\"></a>\r\n");
      out.write("           <nav class=\"tnb\">\r\n");
      out.write("           ");

           		if(id !=null && id.equals("admin")){
           
      out.write("\r\n");
      out.write("           \t\t<div>\r\n");
      out.write("           \t\t\t<a href=\"memList.jsp\">회원관리</a>\r\n");
      out.write("           \t\t\t<a href=\"boardList.jsp\">게시판 관리</a>\r\n");
      out.write("               \t\t<a href=\"logout.jsp\">로그아웃</a>\r\n");
      out.write("           \t\t</div>\r\n");
      out.write("           ");

           		} else if(id != null){
           
      out.write("\r\n");
      out.write("           \t\t<div>\r\n");
      out.write("           \t\t\t<span class=\"id_print\">");
      out.print(name );
      out.write("님</span>\r\n");
      out.write("               \t\t<a href=\"logout.jsp\">로그아웃</a>\r\n");
      out.write("               \t\t<a href=\"memInfo.jsp\">회원정보</a>\r\n");
      out.write("               \t</div>\r\n");
      out.write("           ");
 
           		} else {
           	
      out.write("\r\n");
      out.write("           \t\t<div>\r\n");
      out.write("               \t\t<a href=\"login.jsp\">로그인</a>\r\n");
      out.write("               \t\t<a href=\"join.jsp\">회원가입</a>\r\n");
      out.write("               \t</div>\t       \r\n");
      out.write("           ");

           		}
           
      out.write("\r\n");
      out.write("           </nav>\r\n");
      out.write("           <nav class=\"gnb\">\r\n");
      out.write("               <ul>\r\n");
      out.write("                   <li class=\"item1\">\r\n");
      out.write("                       <a href=\"company.jsp#page1\" class=\"main\">브랜드스토리</a>\r\n");
      out.write("                       <ul class=\"sub\">\r\n");
      out.write("                           <li><a href=\"company.jsp#page1\">브랜드 소개</a></li>\r\n");
      out.write("                           <li><a href=\"company.jsp#page2\">공지사항</a></li>\r\n");
      out.write("                           <li><a href=\"company.jsp#page3\">광고 영상</a></li>\r\n");
      out.write("                       </ul>\r\n");
      out.write("                   </li>\r\n");
      out.write("                   <li class=\"item2\">\r\n");
      out.write("                       <a href=\"menu.jsp#page1\" class=\"main\">메뉴</a>\r\n");
      out.write("                       <ul class=\"sub\">\r\n");
      out.write("                           <li><a href=\"menu.jsp#page1\">전체</a></li>\r\n");
      out.write("                           <li><a href=\"menu.jsp#page2\">버거</a></li>\r\n");
      out.write("                           <li><a href=\"menu.jsp#page3\">세트메뉴</a></li>\r\n");
      out.write("                       </ul>\r\n");
      out.write("                   </li>\r\n");
      out.write("                   <li class=\"item3\">\r\n");
      out.write("                       <a href=\"service.jsp#page1\" class=\"main\">프로모션</a>\r\n");
      out.write("                       <ul class=\"sub\">\r\n");
      out.write("                           <li><a href=\"service.jsp#page1\">전체</a></li>\r\n");
      out.write("                           <li><a href=\"service.jsp#page2\">진행중</a></li>\r\n");
      out.write("                           <li><a href=\"service.jsp#page3\">종료</a></li>\r\n");
      out.write("                       </ul>\r\n");
      out.write("                   </li>\r\n");
      out.write("                   <li class=\"item4\">\r\n");
      out.write("                       <a href=\"custom.jsp#page1\" class=\"main\">고객문의</a>\r\n");
      out.write("                       <ul class=\"sub\">\r\n");
      out.write("                           <li><a href=\"faq.jsp\">자주하는 질문</a></li>\r\n");
      out.write("                           <li><a href=\"qna.jsp\">Q/A</a></li>\r\n");
      out.write("                           <li><a href=\"boardList.jsp\">게시판</a></li>\r\n");
      out.write("                       </ul>\r\n");
      out.write("                   </li>\r\n");
      out.write("                   <li class=\"item5\">\r\n");
      out.write("                       <a href=\"map.jsp\" class=\"main\">매장찾기</a>\r\n");
      out.write("                       <ul class=\"sub\">\r\n");
      out.write("                       </ul>\r\n");
      out.write("                   </li>\r\n");
      out.write("               </ul>\r\n");
      out.write("           </nav>\r\n");
      out.write("       </div>");
      out.write("\r\n");
      out.write("    </header>\r\n");
      out.write("<div class=\"content\">\r\n");
      out.write("    <figure class=\"vs\">\r\n");
      out.write("        <video src=\"vidio/mom.mp4\" autoplay muted loop class=\"vdo\"></video>\r\n");
      out.write("    </figure>\r\n");
      out.write("    <section class=\"page\" id=\"page1\">\r\n");
      out.write("        <div class=\"page_wrap\">\r\n");
      out.write("            <h2 class=\"page_tit\">광고 영상</h2>\r\n");
      out.write("            <ul class=\"lst\">\r\n");
      out.write("                <li class=\"left\">\r\n");
      out.write("                    <iframe name=\"vdo2\" id=\"vdo2\" width=\"816\" height=\"459\" src=\"https://www.youtube.com/embed/b43YTcBvyzY\" title=\"맘스터치 치즈홀릭버거 에멘탈 30\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"right\">\r\n");
      out.write("                    <ul class=\"ico_lst\">\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"https://www.youtube.com/embed/b43YTcBvyzY\" target=\"vdo2\" class=\"icon1\">\r\n");
      out.write("                                <h3 class=\"cate_tit\">맘스터치</h3>\r\n");
      out.write("                                <p class=\"cate_com\">치즈홀릭버거 에멘탈</p>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"https://www.youtube.com/embed/pzPPteotgtg\" target=\"vdo2\" class=\"icon2\">\r\n");
      out.write("                                <h3 class=\"cate_tit\">맘스터치</h3>\r\n");
      out.write("                                <p class=\"cate_com\">언블리버블 버거</p>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"https://www.youtube.com/embed/RtixVPqEvdQ\" target=\"vdo2\" class=\"icon3\">\r\n");
      out.write("                                <h3 class=\"cate_tit\">맘스터치</h3>\r\n");
      out.write("                                <p class=\"cate_com\">인크레더블 버거</p>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <section class=\"page\" id=\"page2\">\r\n");
      out.write("        <div class=\"page_wrap\">\r\n");
      out.write("            <h2 class=\"page_tit\">맘스터치<br>메뉴</h2>\r\n");
      out.write("            <ul class=\"pic_lst\">\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"\">\r\n");
      out.write("                        <img src=\"img/1663630773-JQZAP.png\" alt=\"맘스터치 야채통통치킨버거\" class=\"pic\">\r\n");
      out.write("                        <div class=\"hv_box\">\r\n");
      out.write("                            <h3 class=\"pic_tit\">NEW</h3>\r\n");
      out.write("                            <p class=\"pic_com\">야채통통 치킨 버거</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"\">\r\n");
      out.write("                        <img src=\"img/1660612192-BOPMR.png\" alt=\"맘스터치 갈릭바베큐버거\" class=\"pic\">\r\n");
      out.write("                        <div class=\"hv_box\">\r\n");
      out.write("                            <h3 class=\"pic_tit\">NEW</h3>\r\n");
      out.write("                            <p class=\"pic_com\">갈릭 바베큐 버거</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"\">\r\n");
      out.write("                        <img src=\"img/1655341040-HOKQW.png\" alt=\"맘스터치 어메이징매콤마요버거\" class=\"pic\">\r\n");
      out.write("                        <div class=\"hv_box\">\r\n");
      out.write("                            <h3 class=\"pic_tit\">맘스터치</h3>\r\n");
      out.write("                            <p class=\"pic_com\">어메이징 매콤 마요 버거</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"\">\r\n");
      out.write("                        <img src=\"img/1651127296-ECEIR.png\" alt=\"맘스터치 트리플딥치즈싸이버거\" class=\"pic\">\r\n");
      out.write("                        <div class=\"hv_box\">\r\n");
      out.write("                            <h3 class=\"pic_tit\">맘스터치</h3>\r\n");
      out.write("                            <p class=\"pic_com\">트리플 딥 치즈 싸이 버거</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"\">\r\n");
      out.write("                        <img src=\"img/1647845660-MZBRZ.png\" alt=\"맘스터치 쉬프림싸이플렉스버거\"class=\"pic\">\r\n");
      out.write("                        <div class=\"hv_box\">\r\n");
      out.write("                            <h3 class=\"pic_tit\">맘스터치</h3>\r\n");
      out.write("                            <p class=\"pic_com\">쉬프림 싸이 플렉스 버거</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"\">\r\n");
      out.write("                        <img src=\"img/1616480109-NHROT.png\" alt=\"맘스터치 싸이플렉스버거\" class=\"pic\">\r\n");
      out.write("                        <div class=\"hv_box\">\r\n");
      out.write("                            <h3 class=\"pic_tit\">BEST</h3>\r\n");
      out.write("                            <p class=\"pic_com\">싸이 플렉스 버거</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"\">\r\n");
      out.write("                        <img src=\"img/1647844626-SKNGP.png\" alt=\"맘스터치 화이트갈릭싸이버거\" class=\"pic\">\r\n");
      out.write("                        <div class=\"hv_box\">\r\n");
      out.write("                            <h3 class=\"pic_tit\">맘스터치</h3>\r\n");
      out.write("                            <p class=\"pic_com\">화이트 갈릭 싸이 버거</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"\">\r\n");
      out.write("                        <img src=\"img/1633511562-QIONN.png\" alt=\"맘스터치 텍사스바베큐치킨버거\" class=\"pic\">\r\n");
      out.write("                        <div class=\"hv_box\">\r\n");
      out.write("                            <h3 class=\"pic_tit\">맘스터치</h3>\r\n");
      out.write("                            <p class=\"pic_com\">텍사스 바베큐 치킨 버거</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"\">\r\n");
      out.write("                        <img src=\"img/1616480122-HYWCI.png\" alt=\"맘스터치 양념치킨싸이버거\" class=\"pic\">\r\n");
      out.write("                        <div class=\"hv_box\">\r\n");
      out.write("                            <h3 class=\"pic_tit\">맘스터치</h3>\r\n");
      out.write("                            <p class=\"pic_com\">양념치킨 싸이 버거</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <section class=\"page\" id=\"page3\">\r\n");
      out.write("        <div class=\"page_wrap\">\r\n");
      out.write("            <h2 class=\"page_tit\">믿고 맡길 수 있는<br>WE DISPLAY<br>전문 파트너스</h2>\r\n");
      out.write("            <ul class=\"circle_lst lst1\">\r\n");
      out.write("                <li><a href=\"\"><img src=\"./img/thumb/partner01.png\" alt=\"파트너스01\" class=\"thumb\"></a></li>\r\n");
      out.write("                <li><a href=\"\"><img src=\"./img/thumb/partner02.png\" alt=\"파트너스02\" class=\"thumb\"></a></li>\r\n");
      out.write("                <li><a href=\"\"><img src=\"./img/thumb/partner03.png\" alt=\"파트너스03\" class=\"thumb\"></a></li>\r\n");
      out.write("                <li><a href=\"\"><img src=\"./img/thumb/partner04.png\" alt=\"파트너스04\" class=\"thumb\"></a></li>\r\n");
      out.write("                <li><a href=\"\"><img src=\"./img/thumb/partner05.png\" alt=\"파트너스05\" class=\"thumb\"></a></li>\r\n");
      out.write("                <li><a href=\"\"><img src=\"./img/thumb/partner06.png\" alt=\"파트너스06\" class=\"thumb\"></a></li>\r\n");
      out.write("                <li><a href=\"\"><img src=\"./img/thumb/partner07.png\" alt=\"파트너스07\" class=\"thumb\"></a></li>\r\n");
      out.write("                <li><a href=\"\"><img src=\"./img/thumb/partner08.png\" alt=\"파트너스08\" class=\"thumb\"></a></li>\r\n");
      out.write("                <li><a href=\"\"><img src=\"./img/thumb/partner09.png\" alt=\"파트너스09\" class=\"thumb\"></a></li>\r\n");
      out.write("                <li><a href=\"\"><img src=\"./img/thumb/partner10.png\" alt=\"파트너스10\" class=\"thumb\"></a></li>\r\n");
      out.write("                <li><a href=\"\"><img src=\"./img/thumb/partner11.png\" alt=\"파트너스11\" class=\"thumb\"></a></li>\r\n");
      out.write("                <li><a href=\"\"><img src=\"./img/thumb/partner12.png\" alt=\"파트너스12\" class=\"thumb\"></a></li>\r\n");
      out.write("                <li><a href=\"\"><img src=\"./img/thumb/partner13.png\" alt=\"파트너스13\" class=\"thumb\"></a></li>\r\n");
      out.write("                <li><a href=\"\"><img src=\"./img/thumb/partner14.png\" alt=\"파트너스14\" class=\"thumb\"></a></li>\r\n");
      out.write("                <li><a href=\"\"><img src=\"./img/thumb/partner15.png\" alt=\"파트너스15\" class=\"thumb\"></a></li>\r\n");
      out.write("                <li><a href=\"\"><img src=\"./img/thumb/partner16.png\" alt=\"파트너스16\" class=\"thumb\"></a></li>\r\n");
      out.write("                <li><a href=\"\"><img src=\"./img/thumb/partner17.png\" alt=\"파트너스17\" class=\"thumb\"></a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("</div>\r\n");
      out.write("<footer class=\"ft\">\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("<div class=\"ft_wrap\">\r\n");
      out.write("        <div class=\"ft_logo\"><img src=\"img/logo.png\" alt=\"하단로고\"></div>\r\n");
      out.write("        <div class=\"mid_box\">\r\n");
      out.write("            <nav class=\"fnb\">\r\n");
      out.write("                <a href=\"member01.html\">개인정보 처리 방침</a>\r\n");
      out.write("                <a href=\"member02.html\">이용약관</a>\r\n");
      out.write("                <a href=\"member03.html\">이메일무단수집거부</a>\r\n");
      out.write("            </nav>\r\n");
      out.write("            <p class=\"addr\">\r\n");
      out.write("                ㈜맘스터치앤컴퍼니 | 대표이사 | 김동전 사업자등록번호 676-86-00102<br>\r\n");
      out.write("                서울시 강동구 천호대로 1077 이스트센트럴타워 24,25층<br>\r\n");
      out.write("                통신판매업 신고번호 : 제2015-서울강동-0155호<br>\r\n");
      out.write("                대표전화 1661-4205 | 팩스 02-418-0279, 070-4676-0635  \r\n");
      out.write("            </p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <script>\r\n");
      out.write("    function sel_link(sel){\r\n");
      out.write("        location.href = sel.value;\r\n");
      out.write("    }\r\n");
      out.write("    </script>\r\n");
      out.write("</div>>");
      out.write("\r\n");
      out.write("</footer>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
