/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.23
 * Generated at: 2022-10-26 01:13:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class map_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>맘스터치</title>\r\n");
      out.write("<!-- 메타포 -->\r\n");
      out.write("<!-- 오픈그래프 -->\r\n");
      out.write("<!-- 파비콘 -->\r\n");
      out.write("<link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"wiz_logo/apple-icon-60x60.png\">\r\n");
      out.write("<!-- 각 종 플러그인과 설정 파일 -->\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Nanum+Gothic&family=Noto+Sans+KR&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<!-- 구형 브라우저 html5태그 인식 -->\r\n");
      out.write("<script src=\"js/html5shiv.js\"></script>\r\n");
      out.write("<!-- 구형 브라우저에서 css animation 인식 -->\r\n");
      out.write("<script src=\"js/prefixfree.min.js\"></script>\r\n");
      out.write("<!-- 구형 브라우저에서 미디어쿼리 인식 -->\r\n");
      out.write("<script src=\"js/respond.min.js\"></script>\r\n");
      out.write("<!-- jquery 플러그인 연결 -->\r\n");
      out.write("<script src=\"js/jquery-1.11.1.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/reset2.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/header.css\">\r\n");
      out.write("<style>\r\n");
      out.write("/* header.css */\r\n");
      out.write(".hd { position: fixed;}\r\n");
      out.write("    /* content */\r\n");
      out.write("    .vs { clear:both; width: 100%; height:300px; overflow: hidden; }\r\n");
      out.write("    .vs img { display:block; width: 100%; height:auto; }\r\n");
      out.write("    .bread { clear:both; width: 100%; line-height: 60px; border-bottom:3px solid #eee; }\r\n");
      out.write("    .bread_fr { width: 1200px; margin: 0 auto; }\r\n");
      out.write("    .page { clear:both; width: 100%; min-height:100vh;}\r\n");
      out.write("    .page:after { content:\"\"; display:block; clear:both; }\r\n");
      out.write("    .page_wrap { width: 1200px; margin: 0 auto; }\r\n");
      out.write("\r\n");
      out.write("    .page_title { padding-top: 1em; text-align: center; }\r\n");
      out.write("    .home { color:#333; }\r\n");
      out.write("\r\n");
      out.write("    .frm { border:2px solid #333; padding: 24px; width: 1150px; margin:50px auto; }\r\n");
      out.write("    .frm_tb { display:table; margin:40px auto;  }\r\n");
      out.write("    .frm_tb tr { display:table-row; }\r\n");
      out.write("    .frm_tb td, .frm_tb th { display:table-cell; }\r\n");
      out.write("    .frm_tb th { width:200px; height: 48px;  }\r\n");
      out.write("    .frm_tb td { width:300px; height: 48px; }\r\n");
      out.write("    .frm_tb label:before { content:\"*\"; }\r\n");
      out.write("\r\n");
      out.write("    .in_dt { background-color:#fff; height:32px; line-height: 32px; width: 280px; \r\n");
      out.write("    color:#333; font-size:16px; text-indent:0.5em; }\r\n");
      out.write("    .in_btn { display:block; background-color:#333; min-width:120px; height: 32px; \r\n");
      out.write("    line-height: 32px; border-radius:20px; float:left; margin-left:80px; margin-right:20px; cursor:pointer; }\r\n");
      out.write("    .in_btn:hover { background-color: deepskyblue; }\r\n");
      out.write("\r\n");
      out.write("    /* ul > li 를 테이블 처럼 출력 */\r\n");
      out.write("    .frm_tb { display:table; }\r\n");
      out.write("    .frm_tb li { display:table-row; }\r\n");
      out.write("    .frm_tb .td, .frm_tb .th, .frm_tb .td2 { display:table-cell; }\r\n");
      out.write("    .frm_tb .th { width:200px; }\r\n");
      out.write("    .frm_tb .td { width:200px; }\r\n");
      out.write("    .frm_tb .td2 { width:400px; }\r\n");
      out.write("\r\n");
      out.write("    #map_canvas { margin-bottom:40px; }\r\n");
      out.write("    #contact p { text-align:left;\tpadding-left:30px; line-height:30px; \r\n");
      out.write("\t\tmargin-top:25px;\tpadding-right:25px; }\r\n");
      out.write("\t.map_tab a { display:inline-block; margin:18px; width:150px;\r\n");
      out.write("\ttext-align: center; line-height: 36px; background-color: #34283c; color:#fff; \r\n");
      out.write("\tborder-radius:8px; }\r\n");
      out.write("    </style>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/footer.css\">\r\n");
      out.write("    <script>\r\n");
      out.write("    $(document).ready(function(){\r\n");
      out.write("        $(\".to_top\").attr(\"href\", location.href);\r\n");
      out.write("        $(window).scroll(function(){\r\n");
      out.write("            var ht = $(window).height();\r\n");
      out.write("            var tp = $(this).scrollTop();\r\n");
      out.write("            if(tp>=300){\r\n");
      out.write("                $(\".to_top\").addClass(\"on\");\r\n");
      out.write("                $(\".to_top\").attr(\"href\", location.href);\r\n");
      out.write("            } else {\r\n");
      out.write("                $(\".to_top\").removeClass(\"on\");\r\n");
      out.write("                $(\".to_top\").attr(\"href\", location.href);\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    });    \r\n");
      out.write("    </script>\r\n");
      out.write("    <!--여기부터 -->\r\n");
      out.write("<script src=\"https://maps.googleapis.com/maps/api/js?sensor=false\"></script> \r\n");
      out.write("<script> \r\n");
      out.write("//좌표 값을 바꿔서 입력 위도:37.658827995980204, 경도:126.77512489202539 \r\n");
      out.write("function initialize() {\r\n");
      out.write("  var myLatlng = new google.maps.LatLng(37.658827995980204,126.77512489202539);\r\n");
      out.write("  var mapOptions = {\r\n");
      out.write("    zoom: 17,\r\n");
      out.write("    center: myLatlng\r\n");
      out.write("  }\r\n");
      out.write("  var map = new google.maps.Map(document.getElementById('map_canvas'), mapOptions);\r\n");
      out.write("  var marker = new google.maps.Marker({\r\n");
      out.write("      position: myLatlng,\r\n");
      out.write("      map: map,\r\n");
      out.write("      title: '일산동구청'\t  //레이블을 바꿔서 입력\r\n");
      out.write("  });\r\n");
      out.write("}\r\n");
      out.write("google.maps.event.addDomListener(window, 'load', initialize);\r\n");
      out.write(" </script>\r\n");
      out.write("<!-- 여기까지를 head태그 닫기 전에 복사해서 붙여넣기 -->\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"wrap\">\r\n");
      out.write("<header class=\"hd\">\r\n");
      out.write("    <div class=\"hd_wrap\">\r\n");
      out.write("        <a href=\"index1.jsp\" class=\"logo\"><img src=\"img/logo.png\" alt=\"로고\"></a>\r\n");
      out.write("        <nav class=\"tnb\">\r\n");
      out.write("            <a href=\"login.jsp\">로그인</a>\r\n");
      out.write("            <a href=\"join.jsp\">회원가입</a>\r\n");
      out.write("        </nav>\r\n");
      out.write("        <nav class=\"gnb\">\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li class=\"item1\">\r\n");
      out.write("                    <a href=\"company.jsp#page1\" class=\"main\">브랜드스토리</a>\r\n");
      out.write("                    <ul class=\"sub\">\r\n");
      out.write("                        <li><a href=\"company.jsp#page1\">브랜드 소개</a></li>\r\n");
      out.write("                        <li><a href=\"company.jsp#page2\">공지사항</a></li>\r\n");
      out.write("                        <li><a href=\"company.jsp#page3\">광고 영상</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"item2\">\r\n");
      out.write("                    <a href=\"menu.jsp#page1\" class=\"main\">메뉴</a>\r\n");
      out.write("                    <ul class=\"sub\">\r\n");
      out.write("                        <li><a href=\"menu.jsp#page1\">전체</a></li>\r\n");
      out.write("                        <li><a href=\"menu.jsp#page2\">버거</a></li>\r\n");
      out.write("                        <li><a href=\"menu.jsp#page3\">세트메뉴</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"item3\">\r\n");
      out.write("                    <a href=\"service.jsp#page1\" class=\"main\">프로모션</a>\r\n");
      out.write("                    <ul class=\"sub\">\r\n");
      out.write("                        <li><a href=\"service.jsp#page1\">전체</a></li>\r\n");
      out.write("                        <li><a href=\"service.jsp#page2\">진행중</a></li>\r\n");
      out.write("                        <li><a href=\"service.jsp#page3\">종료</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"item4\">\r\n");
      out.write("                    <a href=\"custom.jsp#page1\" class=\"main\">고객문의</a>\r\n");
      out.write("                    <ul class=\"sub\">\r\n");
      out.write("                        <li><a href=\"custom.jsp#page1\">자주하는 질문</a></li>\r\n");
      out.write("                        <li><a href=\"custom.jsp#page2\">Q/A</a></li>\r\n");
      out.write("                        <li><a href=\"custom.jsp#page3\">게시판</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"item5\">\r\n");
      out.write("                    <a href=\"map.jsp\" class=\"main\">매장찾기</a>\r\n");
      out.write("                    <ul class=\"sub\">\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </nav>\r\n");
      out.write("    </div>\r\n");
      out.write("</header>\r\n");
      out.write("<div class=\"content\">\r\n");
      out.write("    <figure class=\"vs\">\r\n");
      out.write("        <img src=\"img/p_brand_1.jpg\" alt=\"비주얼\">\r\n");
      out.write("    </figure>\r\n");
      out.write("    <div class=\"bread\">\r\n");
      out.write("        <div class=\"bread_fr\">\r\n");
      out.write("            <a href=\"index1.jsp\" class=\"home\">HOME</a> &gt;\r\n");
      out.write("            <span class=\"sel\">매장찾기</span>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <section class=\"page\">\r\n");
      out.write("        <div class=\"page_wrap\">\r\n");
      out.write("            <h2 class=\"page_title\">매장찾기</h2>\r\n");
      out.write("            <div class=\"form_fr\">\r\n");
      out.write("                <form name=\"frm1\" action=\"\" method=\"post\" id=\"loginForm\" class=\"frm\">\r\n");
      out.write("                    <div id=\"naver_map\">\r\n");
      out.write("                        <a href=\"https://naver.me/5D3O2psn\">네이버 지도</a><br><br>\r\n");
      out.write("                        <a href=\"https://goo.gl/maps/tB2Ak61rwpiAFqY5A\">구글 지도</a><br><br>\r\n");
      out.write("                        <div class=\"map_tab\">\r\n");
      out.write("                            <a href=\"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d5962.6399372702!2d126.77119283301745!3d37.65864687370668!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x357c8551df24f16b%3A0xdcfb88d27e947ebf!2z7J287IKw64-Z6rWs7LKt!5e0!3m2!1sko!2skr!4v1666084195271!5m2!1sko!2skr\" target=\"g_map\">일산 캠퍼스</a> &nbsp; \r\n");
      out.write("                            <a href=\"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3165.5692519724917!2d127.02787731558699!3d37.494490036007996!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x357ca158ea750d33%3A0xf29e40ea72daaa48!2z642U7KGw7J2A7Lu07ZOo7YSw7JWE7Lm0642w66-47ZWZ7JuQIOqwleuCqOygkA!5e0!3m2!1sko!2skr!4v1666157571832!5m2!1sko!2skr\" target=\"g_map\">강남 캠퍼스</a> &nbsp; \r\n");
      out.write("                            <a href=\"https://www.google.com/maps/embed?pb=!1m16!1m12!1m3!1d3162.3922389631284!2d126.98227256558856!3d37.569380431722536!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!2m1!1z642U7KGw7J2AIOyiheuhnOy6oO2NvOyKpA!5e0!3m2!1sko!2skr!4v1666157757984!5m2!1sko!2skr\" target=\"g_map\">종로 캠퍼스</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <iframe src=\"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d5962.6399372702!2d126.77119283301745!3d37.65864687370668!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x357c8551df24f16b%3A0xdcfb88d27e947ebf!2z7J287IKw64-Z6rWs7LKt!5e0!3m2!1sko!2skr!4v1666084195271!5m2!1sko!2skr\" width=\"1150\" height=\"500\" style=\"border:0;\" allowfullscreen=\"\" loading=\"lazy\" referrerpolicy=\"no-referrer-when-downgrade\" name=\"g_map\" id=\"g_map\"></iframe>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("</div>\r\n");
      out.write("<footer class=\"ft\">\r\n");
      out.write("    <div class=\"ft_wrap\">\r\n");
      out.write("        <div class=\"ft_logo\"><img src=\"img/logo.png\" alt=\"하단로고\"></div>\r\n");
      out.write("        <div class=\"mid_box\">\r\n");
      out.write("            <nav class=\"fnb\">\r\n");
      out.write("                <a href=\"member01.jsp\">개인정보 처리 방침</a>\r\n");
      out.write("                <a href=\"member02.jsp\">이용약관</a>\r\n");
      out.write("                <a href=\"member03.jsp\">이메일무단수집거부</a>\r\n");
      out.write("            </nav>\r\n");
      out.write("            <p class=\"addr\">\r\n");
      out.write("                ㈜맘스터치앤컴퍼니 | 대표이사 | 김동전 사업자등록번호 676-86-00102<br>\r\n");
      out.write("                서울시 강동구 천호대로 1077 이스트센트럴타워 24,25층<br>\r\n");
      out.write("                통신판매업 신고번호 : 제2015-서울강동-0155호<br>\r\n");
      out.write("                대표전화 1661-4205 | 팩스 02-418-0279, 070-4676-0635  \r\n");
      out.write("            </p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <script>\r\n");
      out.write("        function sel_link(sel){\r\n");
      out.write("            location.href = sel.value;\r\n");
      out.write("        }\r\n");
      out.write("        </script>\r\n");
      out.write("    </div>\r\n");
      out.write("</footer>\r\n");
      out.write("</div>\r\n");
      out.write("<a href=\"#\" class=\"to_top\">↑</a>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
